name: ai_bias
channels:
  - default
dependencies:
  - rtree
  - shapely
  - matplotlib
  - pandas
  - seaborn
  - statsmodels
  - plotly
  - tqdm
  - ipykernel
  - xgboost
  - jupyter
  - pip
  - pip:
    - bayesian-optimization
    - dmatrix2np
